openapi: 3.0.0
info:
  title: PeopleAPI
  description: Simple API that returns People based on Affiliation
  contact:
    email: intdev@apu.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: developers
  description: Operations available to developers
- name: end-users
  description: Operations available to end users
paths:
  /hangout/url:
    post:
      tags:
      - developers
      - end-users
      summary: Redirect the user to the appropriate Google Meet URL, if a URL exists
      description: |
        Redirects the user to the Google Meet, if the Google Meet has been created,
        otherwise an HTML file is sent explaining to the user the Google event has
        not been created yet
      x-exegesis-controller: hangoutController
      operationId: ltiHtmlPost
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        "200":
          description: Not ready, needs authorization
          content:
            text/html:
              schema:
                type: object
        "301":
          description: Redirect to Google Meet
          content:
            text/html:
              schema:
                type: object
        "400":
          description: Class Code not specified
  /oauthcallback:
    get:
      tags:
      - developers
      - end-users
      summary: oAuth redirects here
      description: |
        After a successful authorization, Google should redirect the user
        to this endpoint. Furthermore, this endpoint will create the calendar
        event, save it to the database and return the Google Meet link
      operationId: oAuthCallback
      x-exegesis-controller: authController
      parameters:
      - name: code
        in: query
        description: Authorization code coming from Google
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: state
        in: query
        description: State of the redirect from Google
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "301":
          description: Redirect to Google Meet
          content:
            text/html:
              schema:
                type: object
  /xml:
    get:
      tags:
      - developers
      - end-users
      summary: Returns LTI configuration XML
      description: |
        Returns LTI configuration XML
      x-exegesis-controller: xmlController
      operationId: xmlCallback
      responses:
        "200":
          description: Send XML
          content:
            application/xml:
              schema:
                type: object
