apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: lti-googlemeet
  name: lti-googlemeet
  namespace: "{{ openshift.project }}"
spec:
  replicas: 1
  selector:
    app: lti-googlemeet
    deploymentconfig: lti-googlemeet
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: lti-googlemeet
        deploymentconfig: lti-googlemeet
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: lti-googlemeet
          imagePullPolicy: Always
          name: lti-googlemeet
          ports:
            - containerPort: 3000
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - lti-googlemeet
        from:
          kind: ImageStreamTag
          name: 'lti-googlemeet:latest'
          namespace: intdev
      type: ImageChange
