apiVersion: v1
kind: Service
metadata:
  labels:
    app: lti-googlemeet
  name: lti-googlemeet
  namespace: "{{ openshift.project }}"
spec:
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: lti-googlemeet
    deploymentconfig: lti-googlemeet
