---
- name: Deploy Google Meet LTI project to Openshift
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:

    - name: Create the Openshift Secret that holds the application env
      ose:
        state: present
        definition: "{{ lookup('template', './ose/secret.yml') }}"
        namespace: "{{ openshift.project }}"
        verify_ssl: no

    - name: Create an ImageStream
      ose:
        state: present
        definition: "{{ lookup('template', './ose/image-stream.yml') }}"
        namespace: "{{ openshift.project }}"
        verify_ssl: no

    - name: Create a Build Config
      ose:
        state: present
        definition: "{{ lookup('template', './ose/build-config.yml') }}"
        namespace: "{{ openshift.project }}"
        verify_ssl: no

    - name: Create a Deployment
      ose:
        state: present
        definition: "{{ lookup('template', './ose/deployment-config.yml') }}"
        namespace: "{{ openshift.project }}"
        verify_ssl: no

    - name: Create the Service
      ose:
        state: present
        definition: "{{ lookup('template', './ose/service.yml') }}"
        namespace: "{{ openshift.project }}"
        verify_ssl: no
